import { type RouteConfig, index, route } from "@react-router/dev/routes";

export default [
  index("routes/_index.tsx"),
  route("posts", "routes/posts._index.tsx"),
  route("posts/rss.xml", "routes/posts.rss[.]xml.tsx"),
  route("posts/:slug", "routes/posts.$slug.tsx"),
  route("forum", "routes/forum-layout.tsx", [
    index("routes/forum-home.tsx"),
    route("post/new", "routes/forum-page-new.tsx"),
    route("post/:id", "routes/forum-page-detail.tsx"),
    route("auth/login", "routes/forum-page-login.tsx"),
    route("auth/register", "routes/forum-page-register.tsx"),
    route("auth/forgot-password", "routes/forum-page-forgot.tsx"),
    route("auth/reset-password", "routes/forum-page-reset.tsx"),
    route("auth/authorize", "routes/forum-page-authorize.tsx"),
    route("me", "routes/forum-page-me.tsx"),
    route("u/:id", "routes/forum-page-user.tsx"),
    route("admin", "routes/forum-page-admin.tsx"),
    route("agree", "routes/forum-page-agree.tsx"),
    route("privacy", "routes/forum-page-privacy.tsx"),
  ]),
  route("friends", "routes/friends.tsx"),
  route("sponsors", "routes/sponsors.tsx"),
  route("anime", "routes/anime.tsx"),
  route("cover", "routes/tools.cover.tsx"),
  route("watermark", "routes/tools.watermark.tsx"),
  route("convert", "routes/tools.convert.tsx"),
  route("bilibili-cover", "routes/tools.bilibili-cover.tsx"),
  route("tier", "routes/tools.tier.tsx"),
  route("files", "routes/tools.files.tsx"),
  route("webnovel", "routes/webnovel.tsx"),
  route("webnovel/play/:slug", "routes/webnovel.play.$slug.tsx"),
  route("webnovel/editor", "routes/webnovel.editor.tsx"),
  route("webnovel/format", "routes/webnovel.format.tsx"),
  route("webnovel/me", "routes/webnovel.me.tsx"),
  route("webnovel/:slug", "routes/webnovel.$slug.tsx"),
  route("agree", "routes/agree.tsx"),
  route("privacy", "routes/privacy.tsx"),
  route("*", "routes/catchall.tsx"),
] satisfies RouteConfig;
